const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const packageJson = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const mainProcess = fs.readFileSync(path.join(root, "electron", "main.js"), "utf8");
const bootstrap = fs.readFileSync(path.join(root, "electron", "bootstrap.cjs"), "utf8");
const preload = fs.readFileSync(path.join(root, "electron", "preload.cjs"), "utf8");
const exportUtils = fs.readFileSync(path.join(root, "electron", "export-utils.js"), "utf8");
assert.equal(packageJson.main, "electron/bootstrap.cjs");
assert.equal(packageJson.build.appId, "com.fluxel.studio");
assert.match(mainProcess, /contextIsolation:\s*true/);
assert.match(mainProcess, /nodeIntegration:\s*false/);
assert.match(mainProcess, /sandbox:\s*true/);
assert.match(mainProcess, /setWindowOpenHandler/);
assert.match(mainProcess, /will-navigate/);
assert.match(mainProcess, /did-fail-load/);
assert.match(mainProcess, /render-process-gone/);
assert.match(bootstrap, /startup\.log/);
assert.match(bootstrap, /showErrorBox\("Fluxel could not start"/);
assert.match(bootstrap, /import\("\.\/main\.js"\)/);
assert.match(bootstrap, /uncaughtException/);
assert.match(mainProcess, /fluxel:select-export-directory/);
assert.match(mainProcess, /fluxel:save-image/);
assert.match(mainProcess, /fluxel:select-batch-input-directory/);
assert.match(mainProcess, /fluxel:prepare-batch-input/);
assert.match(mainProcess, /fluxel:read-batch-image/);
assert.match(mainProcess, /fluxel:open-directory/);
assert.match(exportUtils, /path\.isAbsolute\(directory\)/);
assert.match(preload, /selectExportDirectory/);
assert.match(preload, /saveImage/);
assert.match(preload, /selectBatchInputDirectory/);
assert.match(preload, /prepareBatchInput/);
assert.match(preload, /readBatchImage/);
const builtIndex = fs.readFileSync(path.join(root, "dist", "index.html"), "utf8");
assert.match(builtIndex, /\.\/assets\//);
console.log("Desktop shell tests passed: secure renderer, export bridge, navigation guard, and relative production assets.");
